import { useParams } from 'react-router-dom'

export const Recipe = () => {
  const { id } = useParams()
  return (
    <section className='max-w-7xl mx-auto'>
      <div className=' bg-Gray bg-opacity-10 relative'>
        <div className='absolute top-4 left-3 sm:hidden'>
          <p className='text-Gray text-opacity-50'><span className='bg-Gray bg-opacity-5 border-2 border-Gray border-opacity-20  rounded-full px-2 py-1  mr-2'>N</span>Name</p>
        </div>
        <img src='/defaultImage.jpg' alt='image' className='w-full h-80 object-cover' />
      </div>
      <div className='px-2 mt-2'>
        <h1 className='font-extrabold text-Gray text-2xl'>
          Title recipe {id}
        </h1>
        <p className='mt-2 text-Gray text-opacity-70'>
          Here is a summary of the recipe generated by the artificial intelligence
        </p>
        <div className='flex justify-between px-3 mt-2'>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/world.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>Spain</span>
          </div>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/timer.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>30 min</span>
          </div>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/people.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>5 people</span>
          </div>
          <div className='hidden sm:flex items-center gap-1 p-2 '>
            <p className='text-Gray text-opacity-50'><span className='bg-Gray bg-opacity-5 border-2 border-Gray border-opacity-20  rounded-full px-2 py-1  mr-2'>N</span>Name</p>
          </div>
        </div>
        <div className='mt-2'>
          <h3 className='font-extrabold text-Gray'>Ingredients</h3>
          <ul className='list-disc list-inside mt-2 mx-6'>
            <li className='text-Gray text-opacity-70'>Ingredient 1</li>
            <li className='text-Gray text-opacity-70'>Ingredient 2</li>
            <li className='text-Gray text-opacity-70'>Ingredient 3</li>
            <li className='text-Gray text-opacity-70'>Ingredient 4</li>
            <li className='text-Gray text-opacity-70'>Ingredient 5</li>
            <li className='text-Gray text-opacity-70'>Ingredient 6</li>
          </ul>
        </div>
        <div className='mt-3'>
          <h3 className='font-extrabold text-Gray'>Steps</h3>
          <ul className='list-disc list-inside mt-2 mx-6'>
            <li className='text-Gray text-opacity-70'>Step 1</li>
            <li className='text-Gray text-opacity-70'>Step 2</li>
            <li className='text-Gray text-opacity-70'>Step 3</li>
            <li className='text-Gray text-opacity-70'>Step 4</li>
            <li className='text-Gray text-opacity-70'>Step 5</li>
            <li className='text-Gray text-opacity-70'>Step 6</li>
          </ul>
        </div>
      </div>
    </section>
  )
}
