import { Link } from 'react-router-dom'
export const Card = () => {
  const id = '2'
  return (
    <article className='bg-White rounded-xl'>
      <div className='rounded-t-xl bg-Gray bg-opacity-10 relative'>
        <div className='absolute top-4 left-3 '>
          <p className='text-Gray text-opacity-50'><span className='bg-Gray bg-opacity-5 border border-Gray border-opacity-20  rounded-full px-2 py-1  mr-2'>N</span>Name</p>
        </div>
        <img src='/defaultImage.jpg' alt='image' className='w-full h-48 object-cover rounded-t-xl' />
      </div>
      <div className='p-3'>
        <h3 className='text-2xl font-semibold'>Title recipes</h3>
        <p className='text-opacity-70 text-Gray mt-2'>Here is a summary of the recipe generated by the artificial intelligence</p>
        <div className='flex justify-between px-3'>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/world.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>Spain</span>
          </div>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/timer.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>30 min</span>
          </div>
          <div className='flex items-center gap-1 p-2 text-Gray'>
            <img src='/icons/people.svg' alt='World' className='w-8 h-8 opacity-30' />
            <span className='text-Gray text-opacity-50'>5 people</span>
          </div>
        </div>
        <Link to={`recipe/${id}`} className='flex mt-3 gap-1 justify-center items-center font-medium bg-Green hover:opacity-80 active:scale-95 transition-all text-White px-4 py-2 rounded-md'>View recipe</Link>
      </div>
    </article>
  )
}
